#ifndef html_h
#define html_h

String main_page = 
"<html lang='fr'>\r\n"
"  <head>\r\n"
"    <style>\r\n"
"      body, #timer_setup { background-color: #202020 !important; }\r\n"
"      h2, td, a { color: #95A5A6; }\r\n"
"      p { color: white; }\r\n"
"      table, th, td { border: 0px solid black; padding-bottom: 5px; text-align: center; vertical-align: middle;}\r\n"
"      .button { background-color: #4CAF50; border: none; color: white; padding: 15px 22px; float: left; border: 1px solid green; width:120px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px;} \r\n"
"      .button:hover { box-shadow: 0 12px 16px 0 rgba(255,255,255,255.24), 0 17px 50px 0 rgba(255,255,255,0.19) !important;} \r\n"
"      #time { border: none; padding: 15px 0px; float: left; width:240px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px;} \r\n"
"      #datetimepicker {width:120px; float: left; width:120px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px;}; \r\n"
"    </style>\r\n"
"    <meta charset=\"utf-8\">\r\n"
"    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>\r\n"
"    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.css\" />\r\n"
"    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.3.8/jquery.datetimepicker.min.css\"/ >\r\n"
"    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.3.8/jquery.datetimepicker.min.js\"></script>\r\n"
"    <script type=\"text/javascript\">\r\n"
"      $(document).ready(function () {\r\n"
"        jQuery('#datetimepicker').datetimepicker({\r\n"
"          format:'unixtime'\r\n"
"        });\r\n"
"        updateData(); \r\n"
"        setInterval(updateData, 1000);  \r\n"
"      })\r\n"
"      function addZero(i) {\r\n"
"          if (i < 10) {\r\n"
"              i = '0' + i;\r\n"
"          }\r\n"
"          return i;\r\n"
"      }\r\n"
"      function timeConverter(UNIX_timestamp){\r\n"
"        var a = new Date((UNIX_timestamp) * 1000);\r\n"
"        var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];\r\n"
"        var year = a.getFullYear();\r\n"
"        var month = months[a.getUTCMonth()];\r\n"
"        var date = a.getUTCDate();\r\n"
"        var hour = addZero(a.getUTCHours());\r\n"
"        var min = addZero(a.getUTCMinutes());\r\n"
"        var sec = addZero(a.getUTCSeconds());\r\n"
"        var time = date + ' ' + month + ' ' + year + ' ' + hour + ':' + min + ':' + sec ;\r\n"
"        return time;\r\n"
"      }\r\n"
"      function updateData(){ \r\n"
"        $.ajax({ \r\n"
"          type: 'GET', \r\n"
"          contentType: 'application/json; charset=utf-8',\r\n"
"          url: '/fan.json', \r\n"
"          data: {}, \r\n"
"          dataType: 'json',\r\n"
"          success: function (data) { \r\n"
"              console.log(timeConverter(data.fanstate.curLocal_time));\r\n"
"              document.getElementById('time').innerHTML = timeConverter(data.fanstate.curLocal_time);\r\n"
"              if (data.fanstate.autooff_time > data.fanstate.curLocal_time) {\r\n"
"					document.getElementById('autooff').innerHTML = timeConverter(data.fanstate.autooff_time);\r\n"
"              } else {\r\n"
"                   document.getElementById('autooff').innerHTML = \"not set\";\r\n"
"              }\r\n"
"          }\r\n"
"        });\r\n"
"      }\r\n"
"    </script>\r\n"
"    <title>Philips FAN</title>\r\n"
"  </head>\r\n"
"  <body>\r\n"
"    <div class='container-fluid'>\r\n"
"      <div class='row'>\r\n"
"        <div class='col-md-12'>\r\n"
"          <h2>Philips Ventilator</h2>\r\n"
"          <table>\r\n"
"            <tr>\r\n"
"              <td><h4 class ='text-left'>Current Time</h4></td>\r\n"
"              <td><h4 id ='time'></h4></td>\r\n"
"            </tr><tr>\r\n"
"              <td><h4 class ='text-left'>Auto Off at</h4></td>\r\n"
"              <td><h4 id ='autooff'></h4></td>\r\n"
"            </tr>\r\n"
"          </table>\r\n"
"          <table>\r\n"
"            <tr>\r\n"
"              <td><h4 class ='text-left'>Power</h4></td>\r\n"
"              <td><form action='/' method='POST'><button type='button submit' name='power' value='1' class='button'>OFF</button></form></td>\r\n"
"              <td></td>\r\n"
"              <td></td>\r\n"
"            </tr><tr>\r\n"
"              <td><h4 class ='text-left'>Breeze</h4></td>\r\n"
"              <td><form action='' method='POST'><button type='button submit' name='breeze' value='1' class='button'>Toggle</button></form></td>\r\n"
"              <td></td>\r\n"
"              <td></td>\r\n"
"            </tr><tr>\r\n"
"              <td><h4 class ='text-left'>Speed</h4></td>\r\n"
"              <td><form action='/' method='POST'><button type='button submit' name='speed' value='1' class='button'>Slow</button></form></td>\r\n"
"              <td><form action='/' method='POST'><button type='button submit' name='speed' value='2' class='button'>Medium</button></form></td>\r\n"
"              <td><form action='/' method='POST'><button type='button submit' name='speed' value='3' class='button'>Fast</button></form></td>\r\n"
"            </tr><tr>\r\n"
"              <td><h4 class ='text-left'>Swing</h4></td>\r\n"
"              <td><form action='/' method='POST'><button type='button submit' name='swing' value='1' class='button'>Toggle</button></form></td>\r\n"
"              <td></td>\r\n"
"              <td></td>\r\n"
"            </tr>\r\n"
"            </tr><tr>\r\n"
"              <td><h4 class ='text-left'>Auto Off</h4></td>\r\n"
"              <td><form action='/' method='POST'><button type='button submit' name='timer' value='1' class='button'>1 Hour</button></form></td>\r\n"
"              <td><form action='/' method='POST'><button type='button submit' name='timer' value='2' class='button'>2 Hours</button></form></td>\r\n"
"              <td><form action='/' method='POST'><button type='button submit' name='timer' value='3' class='button'>4 Hours</button></form></td>\r\n"
"            </tr><tr>\r\n"
"              <td><h4 class ='text-left'>Auto Off</h4></td>\r\n"
"              <td><form action='/' method='POST'><input type=\"datetimepicker\" name=\"timer\" id=\"datetimepicker\"></td>\r\n"
"              <td><button type='button submit' class='timer_button'>Set Timer</button></td>\r\n"
"              <td></form></td>\r\n"
"            </tr>\r\n"
"          </table>\r\n"
"        </div>\r\n"
"      </div>\r\n"
"    </div>\r\n"
"  </body>\r\n"
"</html>\r\n";

#endif